# Setup
title:               Gerald Lee Jordan
tagline:             'collecting words'
description:         'Gerald.mba'
url:                 https://gerald.mba
baseurl:             /
paginate:            5
permalink:           pretty

# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: /:title/

# About/contact
author:
  name:              Lee Jordan
  url:               https://twitter.com/geraldleejordan
  email:             geraldleejordan@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.0.0
google_analytics_id: #UA-XXXX-Y
timezone: Pacific/Auckland
future: false
